animals = ['bear', 'tiger', 'penguin', 'zebra']
bear = animals[0]
animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
print "python = " + animals[1]
print "bear = " + animals[0]
print "peacock = " + animals[2]
print "kangaroo = " + animals[3]
print "whale = " + animals[4]